Update install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -4,6 +4,9 @@ linesx () {
   printf '%*s' "${COLUMNS:-$(tput cols)}" '' | tr ' ' 🦡 
 }
 
+reset
+export builddr=$(pwd)
+export instance=$1
 
     echo
     echo -e "\e[1;32m B A D G E R - C H A I N Z \e[39m installer\e[0m"
@@ -11,10 +14,16 @@ linesx () {
     linesx
     echo "Installation $(date)" 
     echo "$(hostname)"
+    echo "starting $(sha256sum badger-chainz-secret-mode)" | logger
+    echo "starting $(sha256sum badger-chainz-secret-mode)"
     echo "starting $(sha256sum badger-chainz)" | logger
     echo "starting $(sha256sum badger-chainz)"
     echo "starting $(sha256sum chainz.cfg)" | logger
     echo "starting $(sha256sum chainz.cfg)"
+    echo "starting $(sha256sum badger-weblog.cfg)" | logger
+    echo "starting $(sha256sum badger-weblog.cfg)"
+    echo "starting $(sha256sum badger-weblog)" | logger
+    echo "starting $(sha256sum badger-weblog)"
     echo
 
 # Requirements that this installer will not install by design
@@ -26,17 +35,48 @@ sha256sum $(which gpg) || exit 1
 sha256sum $(which gpg) | logger
 
     echo
-    echo "Press the return key to install, or control+c to abort install script."
+    echo "Type 'logonly' to install badger chains in encrypted-logs-only mode without a transaction block chain, otherwise hit enter to continue or control+c to abort install script."
 
-read resume
+read weblogmode 
 
-    echo "badger-chainz installing..." | logger
-    echo "badger-chainz installing..." 
-    echo "    chmod +x badger-chainz" | logger
-    echo "    chmod +x badger-chainz" 
+if [ $weblogmode = logonly ]; then
 
-chmod +x badger-chainz
-cp badger-chainz /usr/local/sbin/
+    echo "badger-weblog installing..." | logger
+    echo "badger-weblog installing..." 
+    echo "    chmod +x badger-weblog" | logger
+    echo "$(date +%Y%m%d:%H:%M:%S)     chmod +x badger-weblog" 
+
+  chmod +x badger-weblog || exit 1
+
+    echo "    cp badger-weblog /usr/local/sbin/badger-chainz" | logger
+    echo "$(date +%Y%m%d:%H:%M:%S)     cp badger-weblog /usr/local/sbin/badger-chainz"
+
+  cp badger-weblog /usr/local/sbin/badger-chainz || exit 1
+
+    echo "    mkdir -p /opt/badger-chainz/workspace/" | logger
+    echo "$(date +%Y%m%d:%H:%M:%S)     mkdir -p /opt/badger-chainz/workspace/"
+    
+  mkdir -p /opt/badger-chainz/workspace/
+
+    echo "    mkdir -p /opt/badger-chainz/etc/" | logger
+    echo "$(date +%Y%m%d:%H:%M:%S)     mkdir -p /opt/badger-chainz/etc/"
+
+  mkdir -p /opt/badger-chainz/etc/ 
+
+    echo "    cp weblog.cfg /opt/badger-chainz/etc/" | logger
+    echo "$$(date +%Y%m%d:%H:%M:%S)     cp weblog.cfg /opt/badger-chainz/etc/"
+
+  cp badger-weblog.cfg /opt/badger-chainz/etc/ || exit 1
+
+    echo
+    echo -e "\e[1;36m$(date +%Y%m%d:%H:%M:%S)    entering /opt/badger-chainz/workspace/" | logger
+    echo -e "\e[1;36m$(date +%Y%m%d:%H:%M:%S)     entering /opt/badger-chainz/workspace/"
+    
+else
+
+  weblogmode=no
+  chmod +x badger-chainz
+  cp badger-chainz /usr/local/sbin/
 
     echo
     echo -e "\e[1;33mTime to setup the client public key. Paste in a single line of serialized hex encoded secp384r1 public key."
@@ -47,17 +87,17 @@ cp badger-chainz /usr/local/sbin/
     echo -e "\e[1;33mCopy the result of that on to your clipboard buffer and paste it in to the installer then press return."
     echo -e "\e[0m"
     
-read HEXPUB
+  read HEXPUB 
 
     echo
-    echo -e "\e[1;39m    validating that the provided secp384r1 public key is a valid key..."
+    echo -e "\e[1;39m$(date +%Y%m%d:%H:%M:%S)     validating that the provided secp384r1 public key is a valid key..."
     echo
     
-echo $HEXPUB | xxd -r -p > client-setup-pub.pem
-openssl ecparam -name secp384r1 -genkey -noout -out validation.pem
-openssl pkeyutl -derive -inkey validation.pem -peerkey client-setup-pub.pem -out secret.bin || exit 1
-sed -i "s/HEXCUSTPUBKEY/$HEXPUB/g" chainz.cfg || exit 1
-rm -f validation.pem secret.bin
+  echo $HEXPUB | xxd -r -p > client-setup-pub.pem
+  openssl ecparam -name secp384r1 -genkey -noout -out validation.pem
+  openssl pkeyutl -derive -inkey validation.pem -peerkey client-setup-pub.pem -out secret.bin || exit 1
+  sed -i "s/HEXCUSTPUBKEY/$HEXPUB/g" chainz.cfg || exit 1
+  rm -f validation.pem secret.bin
 
     echo
     echo -e "\e[1;39mDo you want to deploy secret mode? Enter Y or N then press enter to continue."
@@ -75,46 +115,105 @@ if [ $secretmode = Y ]; then
     echo -e "\e[1;32mAnd then paste in the key id or key email here and press the enter key. If you are not going to use secret mode, then simply press enter."
     echo -e "\e[0m"
     
-read pgpml
-    
-    echo
-    
-sed -i "s/PGPEMAIL/$pgpml/g" badger-chainz-secret-mode
-
-    echo
-    echo -e "\e[1;32mOverwriting with secret mode:     cp badger-chainz-secret-mode /usr/local/sbin/badger-chainz"
-    echo
-    
-cp badger-chainz-secret-mode /usr/local/sbin/badger-chainz
-    
-  else    
+  read pgpml 
   
     echo
-    echo -e "\e[1;31Not using secret mode."
+    
+  sed -i "s/PGPEMAIL/$pgpml/g" badger-chainz-secret-mode
+
+    echo
+    echo -e "\e[1;32m$(date +%Y%m%d:%H:%M:%S)     Overwriting with secret mode:     cp badger-chainz-secret-mode /usr/local/sbin/badger-chainz"
+    echo
+
+  chmod +x badger-chainz-secret-mode    
+  cp badger-chainz-secret-mode /usr/local/sbin/badger-chainz
+    
+else    
+  
+  secretmode=N
+ 
+    echo
+    echo -e "\e[1;31$(date +%Y%m%d:%H:%M:%S)     Not using secret mode."
     echo
     echo
+    
 fi
 
+  mkdir -p /opt/badger-chainz/workspace/
+
+    echo "$(date +%Y%m%d:%H:%M:%S)     mkdir -p /opt/badger-chainz/etc/" | logger
+    echo "$(date +%Y%m%d:%H:%M:%S)     mkdir -p /opt/badger-chainz/etc/"
+
+  mkdir -p /opt/badger-chainz/etc/ 
+
+    echo "$(date +%Y%m%d:%H:%M:%S)     cp chainz.cfg /opt/badger-chainz/etc/" | logger
+    echo "$(date +%Y%m%d:%H:%M:%S)     cp chainz.cfg /opt/badger-chainz/etc/"
+
+  cp chainz.cfg /opt/badger-chainz/etc/ || exit 1
+
+    echo
+    echo -e "\e[1;36m$(date +%Y%m%d:%H:%M:%S)     entering /opt/badger-chainz/workspace/" | logger
+    echo -e "\e[1;36m$(date +%Y%m%d:%H:%M:%S)    entering /opt/badger-chainz/workspace/"
+    echo
+
+  cd /opt/badger-chainz/
+
+    echo
+    echo -e "\e[1;36m$(date +%Y%m%d:%H:%M:%S)     generating RSA signing private key: secret-rsa.pem"
+    linesx
+    
+  openssl genrsa 4096 > secret-rsa.pem 
+  
+    echo
+    echo -e "\e[1;36m$(date +%Y%m%d:%H:%M:%S)     generating secp384r1 curve private key: secp384r1.pem"
+    linesx
+
+  openssl ecparam -name secp384r1 -genkey -noout -out secp384r1.pem 
+
+    echo
+    echo -e "\e[1;36m$(date +%Y%m%d:%H:%M:%S)     extracting secp384r1 public key : secp384r1.pub"
+    linesx
+
+  openssl ec -in secp384r1.pem -pubout -out secp384r1.pub 
+
+    echo
+    echo -e "\e[1;36m$(date +%Y%m%d:%H:%M:%S)     setting secp384r1.pem as the chain.key: cp secp384r1.pem chain.key"
+    linesx
+
+  cp secp384r1.pem chain.key
+
+    echo
+    echo -e "\e[1;36m$(date +%Y%m%d:%H:%M:%S)     setting secret-rsa.pem as the rsa.pem: cp secret-rsa.pem rsa.pem"
+    linesx
+
+  cp secret-rsa.pem rsa.pem
+
+
+fi
 
 # If NGINX 
 
 if [ -d /var/log/nginx ]; then
     echo "executing..." | logger
     echo "executing..."
-    echo "    rm -f /var/log/nginx/access.log" | logger
-    echo "    rm -f /var/log/nginx/access.log" 
+    echo "$(date +%Y%m%d:%H:%M:%S)     rm -f /var/log/nginx/access.log" | logger
+    echo "$(date +%Y%m%d:%H:%M:%S)     rm -f /var/log/nginx/access.log" 
 
 rm -f /var/log/nginx/access.log
 
-    echo "    mkfifo /var/log/nginx/access.log" | logger
-    echo "    mkfifo /var/log/nginx/access.log"
+    echo "$(date +%Y%m%d:%H:%M:%S)     mkfifo /var/log/nginx/access.log" | logger
+    echo "$(date +%Y%m%d:%H:%M:%S)     mkfifo /var/log/nginx/access.log"
 
 mkfifo /var/log/nginx/access.log 
 
-    echo "    exec 4<>/var/log/nginx/access.log" | logger
-    echo "    exec 4<>/var/log/nginx/access.log"
+    echo "$(date +%Y%m%d:%H:%M:%S)     exec 4<>/var/log/nginx/access.log" | logger
+    echo "$(date +%Y%m%d:%H:%M:%S)     exec 4<>/var/log/nginx/access.log"
 
 exec 4<>/var/log/nginx/access.log
+
+    echo "$(date +%Y%m%d:%H:%M:%S)     restarting nginx"
+    
+systemctl restart nginx || /etc/init.d/nginx restart || echo "could not restart nginx"
 
      linesx
 
@@ -125,20 +224,24 @@ fi
 if [ -d /var/log/httpd/ ]; then
     echo "executing..." | logger
     echo "executing..."
-    echo "    rm -f /var/log/httpd/access_log" | logger
-    echo "    rm -f /var/log/httpd/access_log"
+    echo "$(date +%Y%m%d:%H:%M:%S)     rm -f /var/log/httpd/access_log" | logger
+    echo "$(date +%Y%m%d:%H:%M:%S)     rm -f /var/log/httpd/access_log"
     
 rm -f /var/log/httpd/access_log
 
-    echo "    mkfifo /var/log/httpd/access_log" | logger
-    echo "    mkfifo /var/log/httpd/access_log"
+    echo "$(date +%Y%m%d:%H:%M:%S)     mkfifo /var/log/httpd/access_log" | logger
+    echo "$(date +%Y%m%d:%H:%M:%S)     mkfifo /var/log/httpd/access_log"
 
 mkfifo /var/log/httpd/access_log
 
-    echo "    exec 4<>/var/log/httpd/access_log" | logger
-    echo "    exec 4<>/var/log/httpd/access_log"
+    echo "$(date +%Y%m%d:%H:%M:%S)     exec 4<>/var/log/httpd/access_log" | logger
+    echo "$(date +%Y%m%d:%H:%M:%S)     exec 4<>/var/log/httpd/access_log"
 
 exec 4<>/var/log/httpd/access_log
+
+    echo "$(date +%Y%m%d:%H:%M:%S)     restarting httpd"
+    
+systemctl restart httpd || /etc/init.d/httpd restart || echo "could not restart httpd"
 
     linesx
 
@@ -149,79 +252,51 @@ fi
 if [ -d /var/log/apache2/ ]; then
     echo "executing..." | logger
     echo "executing..."
-    echo "    rm -f /var/log/apache2/access.log" | logger
-    echo "    rm -f /var/log/apache2/access.log"
+    echo "$(date +%Y%m%d:%H:%M:%S)     rm -f /var/log/apache2/access.log" | logger
+    echo "$(date +%Y%m%d:%H:%M:%S)     rm -f /var/log/apache2/access.log"
 
 rm -f /var/log/apache2/access.log
 
-    echo "    mkfifo /var/log/apache2/access.log" | logger
-    echo "    mkfifo /var/log/apache2/access.log"
+    echo "$(date +%Y%m%d:%H:%M:%S)     mkfifo /var/log/apache2/access.log" | logger
+    echo "$(date +%Y%m%d:%H:%M:%S)     mkfifo /var/log/apache2/access.log"
 
 mkfifo /var/log/apache2/access.log
 
-    echo "    exec 4<>/var/log/apache2/access.log" | logger
-    echo "    exec 4<>/var/log/apache2/access.log"
+    echo "$(date +%Y%m%d:%H:%M:%S)     exec 4<>/var/log/apache2/access.log" | logger
+    echo "$(date +%Y%m%d:%H:%M:%S)     exec 4<>/var/log/apache2/access.log"
 
 exec 4<>/var/log/apache2/access.log
+
+    echo "$(date +%Y%m%d:%H:%M:%S)     restarting apache2"
+    
+systemctl restart apache2 || /etc/init.d/apache2 restart || echo "could not restart apache2"
 
     linesx
     
 fi
+    
+    echo
+    echo
+    echo -e "\e[0m$(date +%Y%m%d:%H:%M:%S)     Returning to build dir $builddr"
+    
+cd $builddr
 
+if [ $weblogmode = "logonly" ]; then
+    echo "deployment $(sha256sum badger-weblog)" | logger
+    echo "deployment $(sha256sum badger-weblog)"
+    echo "deployment $(sha256sum badger-weblog.cfg)" | logger
+    echo "deployment $(sha256sum badger-weblog.cfg)"
+  elif [ $secretmode = Y ]; then
+    echo "deployment $(sha256sum badger-chainz-secret-mode)" | logger
+    echo "deployment $(sha256sum badger-chainz-secret-mode)"
+    echo "deployment $(sha256sum chainz.cfg)" | logger
+    echo "deployment $(sha256sum chainz.cfg)"
+  else
     echo "deployment $(sha256sum badger-chainz)" | logger
     echo "deployment $(sha256sum badger-chainz)"
     echo "deployment $(sha256sum chainz.cfg)" | logger
     echo "deployment $(sha256sum chainz.cfg)"
-
-mkdir -p /opt/badger-chainz/workspace/
-
-    echo "    mkdir -p /opt/badger-chainz/etc/" | logger
-    echo "    mkdir -p /opt/badger-chainz/etc/"
-
-mkdir -p /opt/badger-chainz/etc/ 
-
-    echo "    cp chainz.cfg /opt/badger-chainz/etc/" | logger
-    echo "    cp chainz.cfg /opt/badger-chainz/etc/"
-
-cp chainz.cfg /opt/badger-chainz/etc/ || exit 1
-
-    echo
-    echo -e "\e[1;36m    entering /opt/badger-chainz/workspace/" | logger
-    echo -e "\e[1;36m    entering /opt/badger-chainz/workspace/"
-    echo
-
-cd /opt/badger-chainz/
-
-    echo
-    echo -e "\e[1;36m    generating RSA signing private key: secret-rsa.pem" | logger
-    linesx
-    
-openssl genrsa 4096 > secret-rsa.pem
-    
-    echo
-    echo -e "\e[1;36m    generating secp384r1 curve private key: secp384r1.pem"
-    linesx
-
-openssl ecparam -name secp384r1 -genkey -noout -out secp384r1.pem
-
-    echo
-    echo -e "\e[1;36m    extracting secp384r1 public key : secp384r1.pub"
-    linesx
-
-openssl ec -in secp384r1.pem -pubout -out secp384r1.pub
-
-    echo
-    echo -e "\e[1;36m    setting secp384r1.pem as the chain.key: cp secp384r1.pem chain.key"
-    linesx
-
-cp secp384r1.pem chain.key
-
-    echo
-    echo -e "\e[1;36m    setting secret-rsa.pem as the rsa.pem: cp secret-rsa.pem rsa.pem"
-    linesx
-
-cp secret-rsa.pem rsa.pem
-
+fi
 
 # more to come here...
 
@@ -232,5 +307,5 @@ cp secret-rsa.pem rsa.pem
     done
     echo -e "\e[0m"
     echo
-    echo -e "\e[1;32m Install complete!\e[0m"
+    echo -e "\e[1;32m$(date +%Y%m%d:%H:%M:%S)   Install complete!\e[0m"
     echo
